[package]
name = "ctranspiler"
version = "0.1.0"
authors = ["gpi <gpimpale29@gmail.com>"]
edition = "2021"

[dependencies]
serde_json = "1.0.114"
serde = { version = "1.0.197", features = ["derive"] }
num-bigint =  { version = "0.4.4", features = ["serde"] }
num-rational = { version = "0.4.1", features = ["serde"] }
num-traits = "0.2.18"
lsp-types = "0.95.0"
peekmore = "1.3.0"
strum = { version = "0.26.1", features = ["derive"] }
bumpalo = { version = "3.15.3", features = ["allocator_api"] }
hashbrown = { version = "0.14.3", features = ["nightly"] }
indexmap = "2.2.5"
